language: node_js
node_js:
  - "8.9"
env:
  - WEBPACK_VERSION=4
install:
  - npm i yarn -g
  - yarn
branches:
  except:
    - gh-pages
stages:
  - lint
  - build
  - deploy
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - yarn lint
    - stage: build
      script:
        # Build all
        - yarn build
    - stage: deploy
      script:
        # Build all
        - yarn deploy
