language: node_js
node_js:
  - "8.9"
install:
  - npm i yarn -g
  - yarn
  - cd deanon-front
  - yarn
  - cd ..
branches:
  except:
    - gh-pages
stages:
  - lint
jobs:
  include:
    - stage: lint
      script:
        - cd deanon-front
        - yarn lint
