language: node_js
node_js:
  - "8.9"
install:
  - npm i yarn -g
  - yarn
branches:
  except:
    - gh-pages
stages:
  - lint
  - deploy
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - yarn lint
    - stage: deploy
      script:
        - yarn build
        - yarn deploy
