language: node_js
node_js:
  - "10.16.0"
install:
  - cd front && npm i
  - cd ../back && npm i && cd ..
branches:
  except:
    - gh-pages
stages:
  - lint
jobs:
  include:
    - stage: lint
      script:
        - cd front && npm run lint
        - cd ../back && npm run lint