language: node_js
node_js:
  - "10.16.0"
install:
  - yarn
  - cd deanon-front
  - yarn
  - cd ..
branches:
  except:
    - gh-pages
stages:
  - lint-front
  - lint-back
jobs:
  include:     
    - stage: lint
      script:
        - yarn lint
    - stage: build
        script:
        - yarn build-front