version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3-jessie

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - front/node_modules
            - back/node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn build-front